// <auto-generated />
using System;
using GestorGastos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorGastos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619204257_InicialGestorGastos")]
    partial class InicialGestorGastos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorGastos.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Icono")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsDefault = true,
                            Nombre = "Comida"
                        },
                        new
                        {
                            Id = 2,
                            EsDefault = true,
                            Nombre = "Transporte"
                        },
                        new
                        {
                            Id = 3,
                            EsDefault = true,
                            Nombre = "Servicios"
                        },
                        new
                        {
                            Id = 4,
                            EsDefault = true,
                            Nombre = "Entretenimiento"
                        },
                        new
                        {
                            Id = 5,
                            EsDefault = true,
                            Nombre = "Salud"
                        },
                        new
                        {
                            Id = 6,
                            EsDefault = true,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("GestorGastos.Api.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("GestorGastos.Api.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<float>("ConfianzaIA")
                        .HasColumnType("real");

                    b.Property<int>("CuentaId")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionLimpia")
                        .HasColumnType("text");

                    b.Property<string>("DescripcionOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrigenCarga")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RevisadoPorUsuario")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CuentaId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("GestorGastos.Api.Models.Movimiento", b =>
                {
                    b.HasOne("GestorGastos.Api.Models.Categoria", "Categoria")
                        .WithMany("Movimientos")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("GestorGastos.Api.Models.Cuenta", "Cuenta")
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("GestorGastos.Api.Models.Categoria", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("GestorGastos.Api.Models.Cuenta", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
